/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AddGameFmInput
 */
export interface AddGameFmInput {
  /**
   * A brief description of the game.
   * @type {string}
   * @memberof AddGameFmInput
   */
  description: any;
  /**
   * The name to display for this game.
   * @type {string}
   * @memberof AddGameFmInput
   */
  displayName: any;
  /**
   * The name of the new game
   * @type {string}
   * @memberof AddGameFmInput
   */
  name: any;
  /**
   * The URL to the rules of the game.
   * @type {string}
   * @memberof AddGameFmInput
   */
  rulesUrl: any;
}
