/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AddQuestionFmInput
 */
export interface AddQuestionFmInput {
  /**
   * The question to add to a specific game.
   * @type {string}
   * @memberof AddQuestionFmInput
   */
  content: any;
  /**
   *
   * @type {QuestionsQuestionGroupInOut}
   * @memberof AddQuestionFmInput
   */
  group?: any;
  /**
   * The language code for the question.
   * @type {string}
   * @memberof AddQuestionFmInput
   */
  languageCode?: any;
  /**
   * If the game has rounds, specify the round in this field.
   * @type {string}
   * @memberof AddQuestionFmInput
   */
  round?: any;
}
