/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AddStoryFmInput
 */
export interface AddStoryFmInput {
  /**
   *
   * @type {Array&lt;StoryCaertsianCoordinateColor&gt;}
   * @memberof AddStoryFmInput
   */
  drawlosseum?: any;
  /**
   *
   * @type {Array&lt;StoryFibbingItAnswerInOut&gt;}
   * @memberof AddStoryFmInput
   */
  fibbingIt?: any;
  /**
   *
   * @type {string}
   * @memberof AddStoryFmInput
   */
  nickname?: any;
  /**
   *
   * @type {string}
   * @memberof AddStoryFmInput
   */
  question?: any;
  /**
   *
   * @type {Array&lt;StoryQuiblyAnswerInOut&gt;}
   * @memberof AddStoryFmInput
   */
  quibly?: any;
  /**
   *
   * @type {string}
   * @memberof AddStoryFmInput
   */
  round?: any;
}
