/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GamesGameOut
 */
export interface GamesGameOut {
  /**
   * A brief description of the game.
   * @type {string}
   * @memberof GamesGameOut
   */
  description?: any;
  /**
   * The name to display for this game.
   * @type {string}
   * @memberof GamesGameOut
   */
  display_name: any;
  /**
   * If set to true the game is enabled.
   * @type {boolean}
   * @memberof GamesGameOut
   */
  enabled?: any;
  /**
   * The name of the new game.
   * @type {string}
   * @memberof GamesGameOut
   */
  name?: any;
  /**
   * The URL to the rules of the game.
   * @type {string}
   * @memberof GamesGameOut
   */
  rules_url?: any;
}
