/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface QuestionsQuestionOut
 */
export interface QuestionsQuestionOut {
  /**
   * The question to add to a specific game.
   * @type {string}
   * @memberof QuestionsQuestionOut
   */
  content: any;
  /**
   * The type of content question or answer.
   * @type {string}
   * @memberof QuestionsQuestionOut
   */
  type?: QuestionsQuestionOutTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum QuestionsQuestionOutTypeEnum {
  Answer = 'answer',
  Question = 'question',
}
