/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface QuestionsAllQuestionOut
 */
export interface QuestionsAllQuestionOut {
  /**
   * The next question id (for pagination).
   * @type {string}
   * @memberof QuestionsAllQuestionOut
   */
  cursor?: any;
  /**
   * All the question ids.
   * @type {Array&lt;string&gt;}
   * @memberof QuestionsAllQuestionOut
   */
  ids?: any;
}
