/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface QuestionsQuestionGroupInOut
 */
export interface QuestionsQuestionGroupInOut {
  /**
   * The name of the group.
   * @type {string}
   * @memberof QuestionsQuestionGroupInOut
   */
  name: any;
  /**
   * The type of the content group.
   * @type {string}
   * @memberof QuestionsQuestionGroupInOut
   */
  type?: QuestionsQuestionGroupInOutTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum QuestionsQuestionGroupInOutTypeEnum {
  Question = 'question',
  Answer = 'answer',
}
