/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StoryFibbingItAnswerInOut
 */
export interface StoryFibbingItAnswerInOut {
  /**
   *
   * @type {string}
   * @memberof StoryFibbingItAnswerInOut
   */
  answer?: any;
  /**
   *
   * @type {string}
   * @memberof StoryFibbingItAnswerInOut
   */
  nickname?: any;
}
