/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StoryDrawingPoint
 */
export interface StoryDrawingPoint {
  /**
   *
   * @type {number}
   * @memberof StoryDrawingPoint
   */
  x?: any;
  /**
   *
   * @type {number}
   * @memberof StoryDrawingPoint
   */
  y?: any;
}
