/* tslint:disable */
/* eslint-disable */
/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { RequestArgs } from '../base';
import { BASE_PATH, BaseAPI, RequiredError } from '../base';
import type { AddStoryFmInput } from '../models';
import type { StoryStoryInOut } from '../models';
/**
 * StoryApi - axios parameter creator
 * @export
 */
export const StoryApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Add a story.
     * @param {string} gameName The name of the game.
     * @param {AddStoryFmInput} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addStoryFm: async (gameName: string, body?: AddStoryFmInput, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'gameName' is not null or undefined
      if (gameName === null || gameName === undefined) {
        throw new RequiredError(
          'gameName',
          'Required parameter gameName was null or undefined when calling addStoryFm.',
        );
      }
      const localVarPath = `/story/{game_name}`.replace(`{${'game_name'}}`, encodeURIComponent(String(gameName)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      const needsSerialization =
        typeof body !== 'string' || localVarRequestOptions.headers['Content-Type'] === 'application/json';
      localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : body || '';

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteStoryFm: async (gameName: string, storyId: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'gameName' is not null or undefined
      if (gameName === null || gameName === undefined) {
        throw new RequiredError(
          'gameName',
          'Required parameter gameName was null or undefined when calling deleteStoryFm.',
        );
      }
      // verify required parameter 'storyId' is not null or undefined
      if (storyId === null || storyId === undefined) {
        throw new RequiredError(
          'storyId',
          'Required parameter storyId was null or undefined when calling deleteStoryFm.',
        );
      }
      const localVarPath = `/story/{game_name}/{story_id}`
        .replace(`{${'game_name'}}`, encodeURIComponent(String(gameName)))
        .replace(`{${'story_id'}}`, encodeURIComponent(String(storyId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStoryFm: async (gameName: string, storyId: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'gameName' is not null or undefined
      if (gameName === null || gameName === undefined) {
        throw new RequiredError(
          'gameName',
          'Required parameter gameName was null or undefined when calling getStoryFm.',
        );
      }
      // verify required parameter 'storyId' is not null or undefined
      if (storyId === null || storyId === undefined) {
        throw new RequiredError('storyId', 'Required parameter storyId was null or undefined when calling getStoryFm.');
      }
      const localVarPath = `/story/{game_name}/{story_id}`
        .replace(`{${'game_name'}}`, encodeURIComponent(String(gameName)))
        .replace(`{${'story_id'}}`, encodeURIComponent(String(storyId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * StoryApi - functional programming interface
 * @export
 */
export const StoryApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Add a story.
     * @param {string} gameName The name of the game.
     * @param {AddStoryFmInput} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addStoryFm(
      gameName: string,
      body?: AddStoryFmInput,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await StoryApiAxiosParamCreator(configuration).addStoryFm(gameName, body, options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary Delete a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteStoryFm(
      gameName: string,
      storyId: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await StoryApiAxiosParamCreator(configuration).deleteStoryFm(
        gameName,
        storyId,
        options,
      );
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary Get a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getStoryFm(
      gameName: string,
      storyId: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StoryStoryInOut>> {
      const localVarAxiosArgs = await StoryApiAxiosParamCreator(configuration).getStoryFm(gameName, storyId, options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * StoryApi - factory interface
 * @export
 */
export const StoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  return {
    /**
     *
     * @summary Add a story.
     * @param {string} gameName The name of the game.
     * @param {AddStoryFmInput} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addStoryFm(gameName: string, body?: AddStoryFmInput, options?: any): AxiosPromise<string> {
      return StoryApiFp(configuration)
        .addStoryFm(gameName, body, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteStoryFm(gameName: string, storyId: string, options?: any): AxiosPromise<void> {
      return StoryApiFp(configuration)
        .deleteStoryFm(gameName, storyId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get a story.
     * @param {string} gameName The name of the game.
     * @param {string} storyId The id for the story.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStoryFm(gameName: string, storyId: string, options?: any): AxiosPromise<StoryStoryInOut> {
      return StoryApiFp(configuration)
        .getStoryFm(gameName, storyId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * StoryApi - object-oriented interface
 * @export
 * @class StoryApi
 * @extends {BaseAPI}
 */
export class StoryApi extends BaseAPI {
  /**
   *
   * @summary Add a story.
   * @param {string} gameName The name of the game.
   * @param {AddStoryFmInput} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoryApi
   */
  public addStoryFm(gameName: string, body?: AddStoryFmInput, options?: any) {
    return StoryApiFp(this.configuration)
      .addStoryFm(gameName, body, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @summary Delete a story.
   * @param {string} gameName The name of the game.
   * @param {string} storyId The id for the story.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoryApi
   */
  public deleteStoryFm(gameName: string, storyId: string, options?: any) {
    return StoryApiFp(this.configuration)
      .deleteStoryFm(gameName, storyId, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @summary Get a story.
   * @param {string} gameName The name of the game.
   * @param {string} storyId The id for the story.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StoryApi
   */
  public getStoryFm(gameName: string, storyId: string, options?: any) {
    return StoryApiFp(this.configuration)
      .getStoryFm(gameName, storyId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
