image: node:14.17.5

stages:
  - pre
  - test
  - post

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm

before_script:
  - npm ci --cache .npm --prefer-offline

install:dependencies:
  stage: pre
  only:
    - merge_request
    - main
  script:
    - npm ci
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules

publish-docker:test:
  stage: pre
  only:
    - main
  image: docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:test --build-arg MODE=staging .
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:e2e --build-arg MODE=test .
    - docker push ${CI_REGISTRY_IMAGE}:test
    - docker push ${CI_REGISTRY_IMAGE}:e2e

lint:commits:
  stage: test
  only:
    - merge_request
  before_script: []
  script:
    - 'echo ''module.exports = { extends: ["@commitlint/config-conventional"] };'' > commitlint.config.js'
    - npm install -g @commitlint/cli @commitlint/config-conventional
    - git fetch origin ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - commitlint --from=origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} --to=origin/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}

lint:
  stage: test
  only:
    - merge_request
  script:
    - npm run lint

types:check:
  stage: test
  only:
    - merge_request
  script:
    - npm run types:check

format:
  stage: test
  only:
    - merge_request
  script:
    - npm run format:check

test:
  stage: test
  only:
    - merge_request
  script:
    - npm run test -- --passWithNoTests

trigger:e2e:tests:
  stage: post
  only:
    - main
  script:
    - curl -X POST -F token=$BANTER_BUS_TESTS_CI_TRIGGER_TOKEN  -F "variables[SOURCE_TRIGGER]=banter-bus-core-api" -F "variables[DEPLOY_COMMIT]=$CI_COMMIT_SHA" -F ref=main https://gitlab.com/api/v4/projects/28716097/trigger/pipeline
