/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionsQuestionGroupInOut } from './questionsQuestionGroupInOut';


export interface AddQuestionInput { 
    /**
     * The question to add to a specific game.
     */
    content: string;
    group?: QuestionsQuestionGroupInOut;
    /**
     * The language code for the question.
     */
    language_code?: string;
    /**
     * If the game has rounds, specify the round in this field.
     */
    round?: string;
}
