/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoryCaertsianCoordinateColor } from './storyCaertsianCoordinateColor';
import { StoryFibbingItAnswerInOut } from './storyFibbingItAnswerInOut';
import { StoryQuiblyAnswerInOut } from './storyQuiblyAnswerInOut';


export interface AddStoryInput { 
    drawlosseum?: Array<StoryCaertsianCoordinateColor>;
    fibbing_it?: Array<StoryFibbingItAnswerInOut>;
    nickname?: string;
    question?: string;
    quibly?: Array<StoryQuiblyAnswerInOut>;
    round?: string;
}
