/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuestionsAllQuestionOut { 
    /**
     * The next question id (for pagination).
     */
    cursor?: string;
    /**
     * All the question ids.
     */
    ids?: Array<string>;
}
