/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuestionsQuestionGroupInOut { 
    /**
     * The name of the group.
     */
    name: string;
    /**
     * The type of the content group.
     */
    type?: QuestionsQuestionGroupInOut.TypeEnum;
}
export namespace QuestionsQuestionGroupInOut {
    export type TypeEnum = 'question' | 'answer';
    export const TypeEnum = {
        Question: 'question' as TypeEnum,
        Answer: 'answer' as TypeEnum
    }
}
