/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuestionsQuestionOut { 
    /**
     * The question to add to a specific game.
     */
    content: string;
    /**
     * The type of content question or answer.
     */
    type?: QuestionsQuestionOut.TypeEnum;
}
export namespace QuestionsQuestionOut {
    export type TypeEnum = 'answer' | 'question';
    export const TypeEnum = {
        Answer: 'answer' as TypeEnum,
        Question: 'question' as TypeEnum
    }
}
