/**
 * Banter Bus Management API
 * The API specification for the Banter Bus Management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoryDrawingPoint } from './storyDrawingPoint';


export interface StoryCaertsianCoordinateColor { 
    color?: string;
    end?: StoryDrawingPoint;
    start?: StoryDrawingPoint;
}
