FROM node:fermium-buster

ARG USERNAME=node
WORKDIR /app

RUN apt-get update && \
  apt-get install -y sudo && \
  echo ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
  chmod 0440 /etc/sudoers.d/$USERNAME

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history"&& \
  mkdir /commandhistory && \
  touch /commandhistory/.bash_history && \
  chown -R $USERNAME /commandhistory && \
  echo $SNIPPET >> "/home/$USERNAME/.bashrc"

COPY package*.json ./
RUN npm install -g npm && \
  npm install

RUN chown $USERNAME:$USERNAME -R /app
COPY . ./

USER $USERNAME
CMD ["npm", "run", "dev"]
